---
title: "Dashboard"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: embed
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
devtools::install_github("p8105/p8105.datasets")
library(p8105.datasets)

library(plotly)
```

```{r}
data("instacart")
instacart = 
  instacart %>% 
  slice(1:100) # select only 100 rows
```

Column {data-width=650}
-----------------------------------------------------------------------

```{r}
instacart %>%
  count(aisle, name = "n_obs") %>% 
  ggplot(aes(x = aisle, y = n_obs))+
  geom_point() +
  coord_flip() +
  ggtitle("") +
  xlab("aisle name") + ylab("number of items")
```

Column {data-width=350}
-----------------------------------------------------------------------
```{r}
instacart %>% 
  count(department) %>% 
  mutate(department = fct_reorder(department, n)) %>% 
  plot_ly(x = ~department, y = ~n, color = ~department, type = "bar", colors = "viridis")
```

```{r}
instacart %>% 
  mutate(department = fct_reorder(department, order_hour_of_day)) %>% 
  plot_ly(y = ~order_hour_of_day, color = ~department, type = "box", colors = "viridis")
```